apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
        - name: sms-service
          image: your-docker-repo/sms-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/smsmax
            - name: SPRING_DATASOURCE_USERNAME
              value: smsuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: smspassword
